log_region_pct:
  x: 0.2158671586715867
  y: 0.0392156862745098
  w: 0.22140221402214022
  h: 0.0427807486631016

button_point_pct:
  x: 0.5839483394833949
  y: 0.47771836007130125

# log_scroll_point_pct:
#   x: 0.4327   # Scroll bar (right)
#   y: 0.0499   # TOP (latest messages here!)

kill_all_cs2_point_pct:
  x: 0.8496  
  y: 0.7094
  
panel:
  dir: "C:/Users/SinFermera/Desktop/FSM_PANEL v.2.7.1"
  
  first_run:
    initial_wait_seconds: 10
    force_on_ocr_fail: true  # If OCR fails, run clicks anyway
    
    clicks:
      - { x_pct: 0.5747, y_pct: 0.8093, wait_s: 2.0 }  # Click 1
      - { x_pct: 0.5655, y_pct: 0.6631, wait_s: 2.0 }  # Click 2
      - { x_pct: 0.8238, y_pct: 0.7825, wait_s: 2.0 }  # Click 3

steam_route:
  exe: "C:/Users/SinFermera/Desktop/SteamRouteTool/SteamRouteTool.exe"
  process_name: "SteamRouteTool.exe"  # This is critical for duplicate detection!
  launch_with_panel: true

paths:
  # expressvpn_exe:
  #   - "C:/Program Files (x86)/ExpressVPN/expressvpn-ui/ExpressVPN.exe"

  memreduct_exe:
    - "C:/Program Files/Mem Reduct/MemReduct.exe"

  rdpclient_exe:
    - "C:/Users/Farmer7/Downloads/RDPClient/RDPClient/RDPClient.exe"

rdp:
  user1_point_pct:
    x: 0.1902
    y: 0.2754
  user2_point_pct:
    x: 0.2366
    y: 0.3300
  ui_wait_s: 5.0
  dialog_wait_s: 1.0    

rdp_windows:
  # Size for each RDP game window (SixFarmers15, SixFarmers16)
  width: 1616   # Width in pixels
  height: 939  # Height in pixels
  
  # Window search term
  title_search: "SinFermera"